name: Build and Deploy .NET 8 Output

on:
  push:
    branches: [ main ]  # Change if using a different default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: pages-test

      - name: Build project
        run: dotnet build --configuration Release --no-restore
        working-directory: pages-test

      - name: Run app
        run: dotnet run --configuration Release
        working-directory: pages-test

      - name: Deploy output to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages-test/output
          publish_branch: gh-pages

